services:
    webapp:
        build: .
        command: npm run dev
        container_name: trauma-yoga-web
        ports:
            - 3000:3000
        volumes:
            - type: bind
              source: ./
              target: /app
